- id: '1552181244155'
  alias: Set theme on start
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: clear
    service: frontend.set_theme
- id: '1552492002557'
  alias: Enable automations whenever HASS starts
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      entity_id: all
    service: automation.turn_on
- id: '1566509198165'
  alias: Enable Office Control
  trigger:
  - event_data:
      event: 1000
      id: office_control
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: input_boolean.office
    service: input_boolean.turn_off
  - data:
      entity_id: light.office
    service: light.turn_off
- id: '1566509427559'
  alias: Disable Office Control
  trigger:
  - event_data:
      event: 1004
      id: office_control
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: input_boolean.office
    service: input_boolean.turn_on
- id: '1566517473188'
  alias: Enable Common Area Control
  trigger:
  - event_data:
      event: 1000
      id: common_area_control
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: input_boolean.common_area
    service: input_boolean.turn_off
  - data:
      entity_id: input_boolean.dining
    service: input_boolean.turn_off
  - data:
      entity_id: input_boolean.kitchen
    service: input_boolean.turn_off
  - data:
      entity_id: light.common_area
    service: light.turn_off
  - data:
      entity_id: light.dining
    service: light.turn_off
  - data:
      entity_id: light.kitchen
    service: light.turn_off
  - data:
      entity_id: light.common_area_stairs
    service: light.turn_off
  - data:
      entity_id: light.front_entry
    service: light.turn_off
  - data:
      entity_id: switch.led_lights
    service: switch.turn_on
  - data:
      entity_id: media_player.vizio_smartcast
    service: media_player.turn_on
  - data:
      entity_id: media_player.downstairs
      volume_level: '0.85'
    service: media_player.volume_set
  - data:
      entity_id: media_player.downstairs
      media_content_id: http://192.168.86.200:8123/local/audio/thx.mp3
      media_content_type: audio/mp3
    service: media_player.play_media
- id: '1566517785950'
  alias: Disable Common Area Control
  trigger:
  - event_data:
      event: 1004
      id: common_area_control
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: input_boolean.entertainment
    service: input_boolean.turn_off
  - data:
      entity_id: input_boolean.common_area
    service: input_boolean.turn_on
  - data:
      entity_id: input_boolean.dining
    service: input_boolean.turn_on
  - data:
      entity_id: input_boolean.kitchen
    service: input_boolean.turn_on
  - data:
      entity_id: light.common_area
    service: light.turn_on
  - data:
      entity_id: switch.led_lights
    service: switch.turn_off
  - data:
      entity_id: media_player.vizio_smartcast
    service: media_player.turn_off
