- id: zigbee2mqtt_log_level
  alias: Zigbee2mqtt Log Level
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_select.zigbee2mqtt_log_level
    to: debug
  - platform: state
    entity_id: input_select.zigbee2mqtt_log_level
    to: warn
  - platform: state
    entity_id: input_select.zigbee2mqtt_log_level
    to: error
  - platform: state
    entity_id: input_select.zigbee2mqtt_log_level
    to: info
  action:
  - service: mqtt.publish
    data:
      payload_template: '{{ states(''input_select.zigbee2mqtt_log_level'') }}'
      topic: zigbee2mqtt/bridge/config/log_level

- id: '1552181244155'
  alias: Set theme on start
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: clear
    service: frontend.set_theme

- id: '1552492002557'
  alias: Enable automations whenever HASS starts
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      entity_id: all
    service: automation.turn_on
