- id: '1552492002557'
  alias: Enable automations whenever HASS starts
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      entity_id: all
    service: automation.turn_on
- id: '1570716027596'
  alias: Teach Facebox
  trigger:
  - entity_id: switch.facebox
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - service: shell_command.teach_facebox
