- id: '1552181244155'
  alias: Set theme on start
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: clear
    service: frontend.set_theme
- id: '1552492002557'
  alias: Enable automations whenever HASS starts
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      entity_id: all
    service: automation.turn_on
- id: '1566509427559'
  alias: Disable Office Control
  trigger:
  - event_data:
      event: 1004
      id: office_control
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: input_boolean.office
    service: input_boolean.turn_on
