- id: '1552492002557'
  alias: Enable automations whenever HASS starts
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      entity_id: all
    service: automation.turn_on
- id: '1570716027596'
  alias: Teach Facebox
  trigger:
  - entity_id: switch.facebox
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - service: shell_command.teach_facebox
- id: '1572185870324'
  alias: Garage Entry Surveillance
  description: ''
  trigger:
  - entity_id: binary_sensor.mudroom_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.anyone_home
    state: 'off'
  action:
  - data:
      duration: '60'
      filename: /config/www/camera_playback/{{entity_id }}_{{ now().strftime('%Y%m%d_%H%M%S')
        }}.mp4
    service: camera.record
- id: '1572186153891'
  alias: Basement Surveillance
  description: ''
  trigger:
  - entity_id: binary_sensor.basement_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.anyone_home
    state: 'off'
  action:
  - data:
      duration: '60'
      filename: /config/www/camera_playback/{{entity_id }}_{{ now().strftime('%Y%m%d_%H%M%S')
        }}.mp4
    service: camera.record
- id: '1572186204405'
  alias: Rear Entry Surveillance
  description: ''
  trigger:
  - entity_id: binary_sensor.dining_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.anyone_home
    state: 'off'
  action:
  - data:
      duration: '60'
      filename: /config/www/camera_playback/{{entity_id }}_{{ now().strftime('%Y%m%d_%H%M%S')
        }}.mp4
    service: camera.record
- id: '1572186266886'
  alias: Front Entry Surveillance
  description: ''
  trigger:
  - entity_id: binary_sensor.front_entry_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.anyone_home
    state: 'off'
  action:
  - data:
      duration: '60'
      filename: /config/www/camera_playback/{{entity_id }}_{{ now().strftime('%Y%m%d_%H%M%S')
        }}.mp4
    service: camera.record
- id: '1572207707747'
  alias: Common Area Surveillance
  description: ''
  trigger:
  - entity_id: binary_sensor.common_area_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.anyone_home
    state: 'off'
  action:
  - data:
      duration: '60'
      filename: /config/www/camera_playback/{{entity_id }}_{{ now().strftime('%Y%m%d_%H%M%S')
        }}.mp4
    service: camera.record
