homeassistant:
  name: Home Control
  latitude: !secret lat
  longitude: !secret long
  elevation: !secret elevation
  unit_system: imperial
  time_zone:  !secret time_zone
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /tmp
    - /config
  auth_providers:
    - type: homeassistant

##########################################################
## Remote Access & IP Ban
##########################################################


http:
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 3


##########################################################
## Themes
##########################################################


frontend:
  themes: !include themes.yaml
  javascript_version: latest


##########################################################
## Cloud
##########################################################


cloud:
  google_actions:
    filter:
      include_domains:
        - light
        - media_player
        - input_boolean
      include_entities: 
        - switch.candle


##########################################################
## MQTT & DB's
##########################################################


mqtt:
  broker: !secret mqtt_broker
  client_id: homeassistant
  username: !secret mqtt_username
  password: !secret mqtt_password  
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'


##########################################################
## Device Tracking
##########################################################


device_tracker:
  - platform: nmap_tracker
    hosts: 
      - !secret nmap_host1
      - !secret nmap_host2
      - !secret nmap_host3
    exclude:
     - 192.168.86.200
    home_interval: 2


##########################################################
## Xiaomi
##########################################################


xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret xiaomi_key


##########################################################
## History & Recorder Settings
##########################################################


history: 
  include:
    domains:
      - light
      - media_player
      - person
      - sensor
      - binary_sensor
      - image_processing  
  exclude:
    entities:
      - sensor.yr_symbol
      - sun.sun
      - sensor.zigbee2mqtt_bridge_state
      - sensor.time
      - sensor.sunrise
      - sensor.sunset
      - sensor.date
      - sensor.custom_card_tracker

      
recorder:
#  db_url: !secret recorder_db
  include:
    domains:
      - light
      - media_player
      - person
      - sensor
      - binary_sensor
      - image_processing  
  exclude:
    entities:
      - sensor.yr_symbol
      - sun.sun
      - sensor.zigbee2mqtt_bridge_state
      - sensor.time
      - sensor.sunrise
      - sensor.sunset
      - sensor.date
      - sensor.custom_card_tracker
  purge_interval: 0

influxdb:
  database: hass_db
  username: !secret influxdb_username
  password: !secret influxdb_password
  include:
    domains:
      - light
      - media_player
      - person
      - sensor
      - binary_sensor
      - image_processing  
  exclude:
    entities:
      - sensor.yr_symbol
      - sun.sun
      - sensor.zigbee2mqtt_bridge_state
      - sensor.time
      - sensor.sunrise
      - sensor.sunset
      - sensor.date
      - sensor.custom_card_tracker


##########################################################
## TP-Link
##########################################################


tplink:


##########################################################
## Notifications
##########################################################


telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret chat_id

notify:
  - name: NOTIFIER_NAME
    platform: telegram
    chat_id: !secret chat_id


##########################################################
## TTS
##########################################################


tts:
  - platform: google_translate


##########################################################
## Custom Updater
##########################################################


custom_updater:
  track:
    - components
    - cards


##########################################################
## Defaults
##########################################################


default_config:
stream:
ffmpeg:


##########################################################
## logging
##########################################################


logger:
  default: info


##########################################################
## Weather
##########################################################


weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily


##########################################################
## Zigbee Home Automation
##########################################################

# re-enable when ZHA is ready for prime time

#zha:
#  usb_path: /dev/ttyUSB1
#  database_path: /config/zigbee.db


##########################################################
## Zigbee Network Map
##########################################################
 

webhook:

zigbee2mqtt_networkmap:
 
panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    url: '/local/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'


##########################################################
## Include YAML's
##########################################################


group: !include groups.yaml
image_processing: !include image_processing.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switches.yaml
sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
zone: !include zones.yaml
light: !include_dir_merge_list lights/
yeelight: !include lights/yeelights.yaml
camera: !include_dir_merge_list cameras/
media_player: !include media_player.yaml
input_boolean: !include input_boolean.yaml