- platform: vizio
  host: !secret master_bedroom_vizio_host
  access_token: !secret master_bedroom_vizio_token
  name: "Master Suite SmartCast"

- platform: vizio
  host: !secret common_area_vizio_host
  access_token: !secret common_area_vizio_token
  name: "Common Area SmartCast"

- platform: vizio
  host: !secret second_bedroom_vizio_host
  access_token: !secret second_bedroom_vizio_token
  name: "Second Bedroom SmartCast"