title: Hub

resources:
  - url: /local/mini-media-player-bundle.js?v=0.9.2
    type: module

  - url: /customcards/github/maykar/compact-custom-header.js?track=true
    type: module

  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module

views:

##########################################################
## Landing + Home Tab
##########################################################

  - icon: mdi:home-assistant
    title: Second view
    cards:

      - type: weather-forecast
        entity: weather.dark_sky

      - type: map
        aspect_ratio: 100%
        default_zoom: 10
        entities:
          - device_tracker.josiah_jv
          - device_tracker.mariel_pixel_2
          - zone.home

      - type: vertical-stack
        cards:

          - type: picture-glance
            title: Office
            entities:
              - light.desk_light
              - light.loft_light
              - binary_sensor.motion_sensor_158d0001d54b4e
              - sensor.loft_temp
              - media_player.office_display
            camera_image: camera.loft_camera

          - type: picture-glance
            title: Common Area
            entities:
              - light.yeelight_strip_7811dc686a5d
              - binary_sensor.motion_sensor_158d0001b192a4
              - binary_sensor.motion_sensor_158d0001de049c
              - media_player.living_room_speaker
              - sensor.temperature_158d0001c2c0f6
            camera_image: camera.living_room_camera

          - type: picture-glance
            title: Kitchen
            entities:
              - binary_sensor.motion_sensor_158d0001d67135
              - media_player.kitchen_display
              - sensor.temperature_158d00020291d1
            camera_image: camera.stairwell_camera


##########################################################
## Office Tab
##########################################################

  - icon: mdi:monitor-multiple
    title: Office
    cards:

      - type: vertical-stack
        cards:

          - type: entity-button
            entity: binary_sensor.motion_sensor_158d0001d54b4e

          - type: horizontal-stack
            cards:

              - type: sensor
                entity: sensor.loft_temp
                line_color: '#03a9f4'
                hours_to_show: 168
                name: Temperature

              - type: sensor
                entity: sensor.humidity_158d0001f36845
                line_color: '#03a9f4'
                hours_to_show: 168
                name: Humidity

      - type: vertical-stack
        cards:

          - type: picture-glance
            title: Office
            entities:
              - light.desk_light
              - light.loft_light
              - binary_sensor.motion_sensor_158d0001d54b4e
            camera_image: camera.loft_camera

      - type: entities
        title: Media Players
        entities:
           - entity: media_player.office_display
             type: custom:mini-media-player
             group: true

           - entity: media_player.office_speaker
             type: custom:mini-media-player
             group: true


##########################################################
## Kitchen Tab
##########################################################

  - icon: mdi:fridge
    title: Kitchen
    cards:

      - type: vertical-stack
        cards:

          - type: entity-button
            entity: binary_sensor.motion_sensor_158d0001d67135


          - type: horizontal-stack
            cards:

              - type: sensor
                entity: sensor.temperature_158d00020291d1
                line_color: '#03a9f4'
                hours_to_show: 168
                name: Temperature

              - type: sensor
                entity: sensor.humidity_158d00020291d1
                line_color: '#03a9f4'
                hours_to_show: 168
                name: Humidity

      - type: vertical-stack
        cards:

          - type: picture-glance
            title: Kitchen
            entities:
              - binary_sensor.motion_sensor_158d0001d67135
              - media_player.kitchen_display
              - sensor.temperature_158d00020291d1
            camera_image: camera.stairwell_camera

          - type: media-control
            entity: media_player.kitchen_display


##########################################################
## Common Area Tab
##########################################################

  - icon: mdi:sofa
    title: Common Area
    cards:

      - type: vertical-stack
        cards:

          - type: entity-button
            entity: binary_sensor.motion_sensor_158d0001b192a4

          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.temperature_158d0001c2c0f6
                line_color: '#03a9f4'
                hours_to_show: 168
                name: Temperature

              - type: sensor
                entity: sensor.humidity_158d0001c2c0f6
                line_color: '#03a9f4'
                hours_to_show: 168
                name: Humidity


      - type: vertical-stack
        cards:

          - type: picture-glance
            title: Common Area
            entities:
              - light.yeelight_strip_7811dc686a5d
              - binary_sensor.motion_sensor_158d0001b192a4
              - media_player.living_room_speaker
            camera_image: camera.living_room_camera

          - type: media-control
            entity: media_player.living_room_speaker


##########################################################
## Bedroom Tab
##########################################################

  - icon: mdi:hotel
    title: Bedroom
    cards:

      - type: vertical-stack
        cards:

          - type: horizontal-stack
            cards:

              - type: entity-button
                entity: binary_sensor.motion_sensor_158d0001ae9fd0

              - type: entity-button
                entity: binary_sensor.door_window_sensor_158d0001e72b89

          - type: horizontal-stack
            cards:

              - type: sensor
                entity: sensor.temperature_158d0001f41668
                line_color: '#03a9f4'
                hours_to_show: 168
                name: Humidity

              - type: sensor
                entity: sensor.humidity_158d0001f41668
                line_color: '#03a9f4'
                hours_to_show: 168
                name: Humidity


   
      - type: vertical-stack
        cards:

          - type: light
            entity: light.jv_nightstand
            name: JV

          - type: light
            entity: light.mb_nightstand
            name: MB

          - type: light
            entity: light.gateway_light_7811dcb36941
            name: Nighlight         


##########################################################
## Docker Tab
##########################################################

  - icon: mdi:docker
    title: Docker
    cards:

          - type: vertical-stack
            cards:

              - type: sensor
                entity: sensor.glances_containers_active
                title: Containers
               
              - type: sensor
                entity: sensor.cpu_speed
                line_color: '#03a9f4'
                hours_to_show: 168


              - type: sensor
                entity: sensor.glances_containers_cpu_used
                line_color: '#03a9f4'
                hours_to_show: 168


          - type: vertical-stack
            cards:

              - type: entity-button
                entity: script.restart_hass
                tap_action: toggle
                name: Home Assistant

              - type: horizontal-stack
                cards:


                  - type: entity-button
                    entity: script.restart_organizr
                    tap_action: toggle
                    name: Organizr

                  - type: entity-button
                    entity: script.restart_plex
                    tap_action: toggle
                    name: Plex

              - type: horizontal-stack
                cards:

                  - type: entity-button
                    entity: script.restart_portainer
                    tap_action: toggle
                    name: Portainer

                  - type: entity-button
                    entity: script.restart_syncthing
                    tap_action: toggle
                    name: Syncthing

              - type: horizontal-stack
                cards:

                  - type: entity-button
                    entity: script.restart_cadddy
                    tap_action: toggle
                    name: Caddy
                    icon: mdi:restart

                  - type: entity-button
                    entity: script.restart_grafana
                    tap_action: toggle
                    name: Grafana


##########################################################
## Settings Tab
##########################################################

  - icon: mdi:settings
    title: Settings
    cards:

          - type: vertical-stack
            cards:

              - type: sensor
                entity: sensor.cpu_speed
                line_color: '#03a9f4'
                hours_to_show: 168

              - type: sensor
                entity: sensor.glances_cpu_temp
                line_color: '#03a9f4'
                hours_to_show: 168
                unit: f

          - type: vertical-stack
            cards:

              - type: sensor
                entity: sensor.wifi_status
                line_color: '#03a9f4'
                hours_to_show: 168

              - type: sensor
                entity: sensor.wifi_uptime
                line_color: '#03a9f4'
                hours_to_show: 168

              - type: sensor
                entity: sensor.wifi_last_restart
                line_color: '#03a9f4'
                hours_to_show: 168


##########################################################
## Lights Tab
##########################################################

  - icon: mdi:lightbulb
    title: Lights
    cards:

      - type: light
        entity: light.living_room_ambience
        name: Ambience

      - type: light
        entity: light.desk_light
        name: Desk

      - type: light
        entity: light.loft_light
        name: Loft

      - type: light
        entity: light.jv_nightstand
        name: Josiah

      - type: light
        entity: light.mb_nightstand
        name: Mariel

      - type: light
        entity: light.gateway_light_7811dcb36941
        name: Nightlight 


##########################################################
## Speakers Tab
##########################################################

  - icon: mdi:google-home
    title: Speakers
    cards:

        - type: entities
          title: Media Players
          entities:
            - entity: media_player.living_room_speaker
              icon: mdi:google-home
              type: custom:mini-media-player
              group: true

            - entity: media_player.office_speaker
              type: custom:mini-media-player
              icon: mdi:google-home
              group: true

            - entity: media_player.office_display
              type: custom:mini-media-player
              group: true

            - entity: media_player.kitchen_display
              type: custom:mini-media-player
              group: true          
