- platform: group
  name: Basement Group
  entities:
    - light.basement_light_1
    - light.basement_light_2
    - light.basement_light_3
    - light.basement_4

- platform: group
  name: Second Bedroom
  entities:
    - light.second_bedroom1
    - light.second_bedroom2