##########################################################
## Google Wifi
##########################################################

- platform: google_wifi
  name: 'Wifi'
  monitored_conditions:
  - status
  - uptime
  - last_restart