##########################################################
## Plex
##########################################################


- platform: plex
  token: !secret plex_token


##########################################################
## Zigbee2mqtt Bridge
##########################################################


- platform: mqtt
  name: Zigbee2mqtt Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:zigbee