##########################################################
## CPU Performance & Utilities
##########################################################          

- platform: cpuspeed      

- platform: time_date
  display_options:
    - time
    - date

- platform: yr

- platform: uptime
  name: Hub Uptime
  unit_of_measurement: days
